import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";
import { Toaster } from "react-hot-toast";
import CartContextProvider from "@/components/Context/CartContext";
import Footer from "@/components/Footer/Footer";
import MySessionProvider from "@/components/MySessionProvider/MySessionProvider";
import WishlistContextProvider from "@/components/Context/WishlistContext";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <MySessionProvider>
          <WishlistContextProvider>
            <CartContextProvider>
              <Navbar/>
              <div className="container mx-auto">
              {children}
              </div>
              <Footer/>
              <Toaster />
        </CartContextProvider>
          </WishlistContextProvider>
        </MySessionProvider>

      </body>
    </html>
  );
}
